---
title: "Late presentation of chronic condition diagnoses table using reactable"
author: '[Paul Seamer](mailto:paulseamer@nhs.net)'
date: "`r lubridate::today()`"
output:
  html_document:
    keep_md: FALSE
    css: "diagnosis_react_tbls.css"
---

```{r, setup, include=FALSE}
# packages
library("tidyverse")
library("here")
library("reactable")
library("htmltools")
# lubridate via namespace

# functions
source(here("R", "fx_react_tbl.R"))
```

```{r, read, include=FALSE}
ip_grp <- readRDS(here("data", "grouped_ip_diags.rds"))
ed_grp <- readRDS(here("data", "grouped_ed_diags.rds"))

# inpatient
ip_dat <- ip_grp |>
  filter(grpnm == "Late presentation of chronic condition") |> 
  select(diagnm, icd10, p2, u) |>
  arrange(desc(u))

short_nms <- tribble(
  ~ icd10, ~ shortnm,
  "J210", "Acute bronchiolitis due to RSV",
  "J121", "RSV pneumonia",
  "J211", "Acute bronchiolitis hu. metapneumovirus",
  "B348", "Other viral infections, unspec. site",
  "J123", "Human metapneumovirus pneumonia",
  "B341", "Entovirus infection, unspec. site",
  "J988", "Other spec. respiratory disorders",
  "J218", "Acute bronchiolitis other organisms",
  "J219", "Acute bronchiolitis, unspec.",
  "J122", "Parainfluenza virus pneumonia",
  "B000", "Eczema herpeticum"
)

ip_dat <- ip_dat |> 
  left_join(short_nms, by = "icd10") |> 
  mutate(shortnm = ifelse(is.na(shortnm), diagnm, shortnm)) |> 
  select(shortnm, p2, u) |> 
  rename(diagnm = shortnm)

# ED
ed_dat <- ed_grp |>
  filter(grpnm == "Late presentation of chronic condition") |> 
  select(diagnm, p2, u) |>
  arrange(desc(u))

short_nms <- tribble(
  ~ diagnm, ~ shortnm,
  "Acute suppurative otitis media with spontaneous rupture of ear drum", "Otitis media with rupture of ear drum",
  "Viral disease characterized by exanthem", "Viral disease with exanthem",
)

ed_dat <- ed_dat |> 
  left_join(short_nms, by = "diagnm") |> 
  mutate(shortnm = ifelse(is.na(shortnm), diagnm, shortnm)) |> 
  select(shortnm, p2, u) |> 
  rename(diagnm = shortnm)
```

```{r, react-tbl-ip, echo=FALSE}
tbl <- build_react_tbl(ip_dat, units = "Admis", colwidth = c(240, 200, 200))

div(
  class = "late-presentation-ip-rtbl",
  div(
    class = "rtbl-title",
    "Inpatient diagnoses for late presentation of chronic condition"
  ),
  htmlwidgets::appendContent(
    tbl,
    htmltools::tags$span(
      class = "rtbl-src",
      p("Source(s): Strategy Unit analysis; National Commissioning Dataset Repository.")
    )
  )
)
```

```{r, react-tbl-ed, echo=FALSE}
tbl <- build_react_tbl(ed_dat, units = "Visits", colwidth = c(240, 200, 200))

div(
  class = "late-presentation-ed-rtbl",
  div(
    class = "rtbl-title",
    "ED diagnoses for late presentation of chronic condition"
  ),
  htmlwidgets::appendContent(
    tbl,
    htmltools::tags$span(
      class = "rtbl-src",
      p("Source(s): Strategy Unit analysis; National Commissioning Dataset Repository.")
    )
  )
)
```

```{r, google-fonts, echo=FALSE}
# source Google fonts
htmltools::tags$link(
  href = "https://fonts.googleapis.com/css?family=Work+Sans:400,700|Fira+Mono&display=fallback",
  rel = "stylesheet"
)
```
