---
title: "COVID-19 diagnoses table using reactable"
author: '[Paul Seamer](mailto:paulseamer@nhs.net)'
date: "`r lubridate::today()`"
output:
  html_document:
    keep_md: FALSE
    css: "diagnosis_react_tbls.css"
---

```{r, setup, include=FALSE}
# functions
source(here::here("R", "fx_react_tbl.R"))
source(here::here("R", "fx_react_tbl_div.R"))
```

```{r, read, include=FALSE}
ed_grp <- readRDS(here("data", "grouped_ed_diags.rds"))
ip_grp <- readRDS(here("data", "grouped_ip_diags.rds"))

# ED
ed_dat <- ed_grp |>
  filter(grpnm == "Covid-19") |> 
  select(diagnm, p2, u) |>
  arrange(desc(u))

# inpatient
ip_dat <- ip_grp |>
  filter(grpnm == "Covid-19") |> 
  select(diagnm, icd10, p1, p2, u) |> 
  mutate(diagnm = case_when(
    str_detect(icd10, "^U0") ~ "COVID-19", TRUE ~ as.character(diagnm)),
    icd10 = case_when(
    str_detect(icd10, "^U0") ~ "U07", TRUE ~ as.character(icd10)),
    ) |> 
  group_by(diagnm, icd10) |>  
  summarise(across(p1:p2, sum), u = max(u)) |> 
  ungroup() |> 
  mutate(u = p2 / p1) |> 
  select(-p1) |> 
  arrange(desc(u))

short_nms <- tribble(
  ~ icd10, ~ shortnm,
  "Z115", "Special screen. exam. oth. viral diseases",
  "P288", "Oth. spec. respiratory cond. of newborn",
  "M303", "Mucocutaneous lymph node sdr. (Kawasaki)"
  )

ip_dat <- ip_dat |> 
  left_join(short_nms, by = "icd10") |> 
  mutate(shortnm = ifelse(is.na(shortnm), diagnm, shortnm)) |> 
  select(shortnm, p2, u) |> 
  rename(diagnm = shortnm)
```

```{r, react-tbl-ed, echo=FALSE}
tbl <- build_react_tbl(ed_dat, units = "Visits", colwidth = c(240, 200, 200))

react_tbl_div(tbl, selector = "rtbl-grp-ed", title = "ED diagnoses for Covid-19")
```

```{r, react-tbl-ip, echo=FALSE}
tbl <- build_react_tbl(ip_dat, units = "Admis.", colwidth = c(240, 200, 200))

react_tbl_div(tbl, selector = "rtbl-grp-ip", title = "Inpatient diagnoses for Covid-19")
```

```{r, google-fonts, echo=FALSE}
g_fonts
```
