# Update diagnosis groups
# 871_health_effects_reduced_care_covid


# README----
# update the diagnosis groups generated by initial_diagnosis_grping.R
# there are 2 reasons why final grouping differs from the original 
# classification produced by Simon Bourne using 871_diagnosis_grouper_app
# 1) ED only - here, the original class. is applied to a sample of providers 
# that code above a threshold, whereas the original class. was based on an earlier 
# version of raw data that used full ED population (not a sample), so there are 
# some ED  diagnoses that were previously placed in a group that don't 
# appear in the updated list of diagnoses that increased significantly in the sample
# 2) initial groupings are revised to reflect outcome of discussion with SW 2022-06-17
# some diagnoses move group, some groups are removed/renamed/collapsed and new 
# groups created


# packages----
library("tidyverse")
library("here")
library("data.table")


# functions ----
source(here("R", "fx_utilities.R"))




# 1 read data----
chg_ed        <- readRDS(here("data", "spc_ed_diags_increased.rds"))
chg_ip        <- readRDS(here("data", "spc_ip_diags_increased.rds"))
class_dat     <- readRDS(here("data", "initial_diagnosis_grping.rds"))
procd_th_plus <- readRDS(here("data", "sample_providers_code_above_threshold.rds"))

ed_dat <- fread(
  here("raw_data", "ed_diag_dat_20220719.csv"),
  na = c("NULL", "NA"))




# 2 wrangle----
ed_class <- class_dat |> filter(pod == "ed")
ip_class <- class_dat |> filter(pod == "ip")

ed_dat <- clean_raw_dat(ed_dat, ed = TRUE) |> filter(isoyrwk != "2022-13")




# 3 update grps based on sample provs----
ed_grp <- chg_ed |> 
  left_join(
    ed_class |> 
      select(diagnm, grpnm),
    by = "diagnm"
  )

ip_grp <- chg_ip |> 
  left_join(
    ip_class |>  
      select(diagnm, grpnm),
    by = "diagnm"
  )

# see README - these diags increased in whole ED population and hence incl. in 
# initial class. but did not increase in sample providers 
ed_class |>
  left_join(chg_ed, by = "diagnm") |> 
  filter(is.na(p1)) |>
  select(pod:p2.x)

# examples of affected diagnoses
# congenital dislocation of hip and influenza increased in whole ED population 
# but did not increase in sample providers
ed_dat |>
  filter(!is.na(tmper)) |>
  group_by(tmper, diagnm) |>
  summarise(n = sum(n_visits)) |>
  pivot_wider(names_from = "tmper", values_from = "n") |>
  filter(str_detect(diagnm, "Congenital dislocation"))

ed_dat |>
  filter(procd %in% procd_th_plus) |> 
  filter(!is.na(tmper)) |>
  group_by(tmper, diagnm) |>
  summarise(n = sum(n_visits)) |>
  pivot_wider(names_from = "tmper", values_from = "n") |>
  filter(str_detect(diagnm, "Congenital dislocation"))

ed_dat |>
  filter(!is.na(tmper)) |>
  group_by(tmper, diagnm) |>
  summarise(n = sum(n_visits)) |>
  pivot_wider(names_from = "tmper", values_from = "n") |>
  filter(str_detect(diagnm, "Influenza"))

ed_dat |>
  filter(procd %in% procd_th_plus) |> 
  filter(!is.na(tmper)) |>
  group_by(tmper, diagnm) |>
  summarise(n = sum(n_visits)) |>
  pivot_wider(names_from = "tmper", values_from = "n") |>
  filter(str_detect(diagnm, "Influenza"))




# 4 update grps----
# ED visits
ed_grp_new <- ed_grp |> 
  rename(old_grpnm = grpnm) |> 
  # rename grps
  mutate(grpnm = case_when(
    old_grpnm == "covid-19" ~ "Covid-19",
    old_grpnm == "primary care late presentation" ~ "Late presentation of chronic conditions",
    # collapse primary care follow-up groups
    old_grpnm == "primary care fup ltc" ~ 
      "Exacerbation of chronic conditions",
    old_grpnm == "primary care fup ltc - emergency" ~ 
      "Exacerbation of chronic conditions",
    old_grpnm == "emergency eye services" ~ "Eye conditions and injuries",
    old_grpnm == "antenatal services" ~ "Complications of pregnancy",
    old_grpnm == "isolation older people" ~ "Social isolation among older people",
    old_grpnm == "surgical fup" ~ "Postoperative problems",
    old_grpnm == "mental health" ~ NA_character_,
    old_grpnm == "alcohol" ~ "Effects of alcohol misuse",
    old_grpnm == "domestic violence" ~ "Physical injuries",
    old_grpnm == "sedentary lifestyles" ~ "Spinal or back conditions",
    TRUE ~ as.character(old_grpnm))
  ) |> 
  # new grp - common infections of childhood
  mutate(grpnm = case_when(
    diagnm %in% c(
      "Bronchiolitis",
      "Viral wheeze",
      "Otitis media",
      "Hand foot and mouth disease",
      "Eczema herpeticum",
      "Viral disease characterized by exanthem",
      "Otitis externa",
      "Acute suppurative otitis media with spontaneous rupture of ear drum",
      "Upper respiratory infection"
      ) ~ "Common infections of childhood",
    TRUE ~ grpnm)
    ) |> 
  # new grp - other childhood conditions
  mutate(grpnm = case_when(
    grpnm == "primary care children" ~ "Other childhood conditions",
    TRUE ~ grpnm)
  ) |> 
  # new grp - eating disorders
  mutate(grpnm = case_when(
    diagnm == "Eating disorder" ~ "Eating disorders",
    TRUE ~ grpnm)
  ) |> 
  # move blunt injury of eye
  mutate(grpnm = case_when(
    diagnm == "Blunt injury of eye" ~ "Physical injuries",
    TRUE ~ grpnm)
  ) |> 
  # drop thrombocytopenic disorder from other childhood conditions group
  # (data suggest predominantly adult cases)
  filter(diagnm != "Thrombocytopenic disorder") 

# emergency admissions
ip_grp_new <- ip_grp |> 
  rename(old_grpnm = grpnm) |> 
  mutate(
    icd10 = str_sub(diagnm, 1L, 4),
    diagnm = str_sub(diagnm, 7, -1L)
    ) |> 
  # rename grps
  mutate(grpnm = case_when(
    old_grpnm == "covid-19" ~ "Covid-19",
    old_grpnm == "primary care late presentation" ~ "Late presentation of chronic conditions",
    # collapse primary care follow-up groups
    old_grpnm == "primary care fup ltc" ~ 
      "Exacerbation of chronic conditions",
    old_grpnm == "primary care fup ltc - emergency" ~ 
      "Exacerbation of chronic conditions",
    old_grpnm == "emergency eye services" ~ "Eye conditions and injuries",
    old_grpnm == "antenatal services" ~ "Complications of pregnancy",
    old_grpnm == "isolation older people" ~ "Social isolation among older people",
    old_grpnm == "surgical fup" ~ "Postoperative problems",
    old_grpnm == "mental health" ~ NA_character_,
    old_grpnm == "alcohol" ~ "Effects of alcohol misuse",
    old_grpnm == "domestic violence" ~ "Physical injuries",
    old_grpnm == "sedentary lifestyles" ~ "Spinal or back conditions",
    TRUE ~ as.character(old_grpnm))
  ) |> 
  # new grp - common infections of childhood
  mutate(grpnm = case_when(
    icd10 %in% c(
      "J210",
      "J211",
      "J218",
      "J219",
      "J121",
      "J122",
      "J123",
      "J988",
      "B000",
      "B341",
      "B348"
    ) ~ "Common infections of childhood",
    TRUE ~ grpnm)
  ) |> 
  # new grp - other childhood conditions
  mutate(grpnm = case_when(
    grpnm == "primary care children" ~ "Other childhood conditions",
    TRUE ~ grpnm)
  ) |> 
  # new grp - eating disorders
  mutate(grpnm = case_when(
    icd10 %in% c("F500", "F508", "F509", "R630") ~ "Eating disorders",
    TRUE ~ grpnm)
  ) |> 
  # U ICD10 codes in covid group
  mutate(grpnm = case_when(
    icd10 = str_detect(icd10, "^U07") ~ "Covid-19",
    TRUE ~ grpnm)
  ) |> 
  # move E113 diabetes eye complications
  mutate(grpnm = case_when(
    icd10 == "E113" ~ "Exacerbation of chronic conditions",
    TRUE ~ grpnm)
  ) |>  # remove R930 from effects of physical violence
  mutate(grpnm = case_when(
    icd10 == "R930" ~ NA_character_,
    TRUE ~ grpnm
  ))

# summarise changes
ed_grp_new |> 
  filter(if_any(contains("grpnm"), ~ !is.na(.x))) |> 
  select(diagnm, contains("grpnm"))

ip_grp_new |> 
  filter(if_any(contains("grpnm"), ~ !is.na(.x))) |> 
  select(diagnm, contains("grpnm"))




# 5 save----
saveRDS(ed_grp_new, here("data", "grouped_ed_diags.rds"))
saveRDS(ip_grp_new, here("data", "grouped_ip_diags.rds"))

